"""adding new url handle

Revision ID: 79264641f5d3
Revises: d2d3be567225
Create Date: 2020-09-25 11:30:27.626626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79264641f5d3'
down_revision = 'd2d3be567225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###
