"""adding shop sim table

Revision ID: 80541889807e
Revises: 
Create Date: 2020-09-24 11:40:52.651363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80541889807e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_sim',
    sa.Column('shop_id', sa.String(length=45), nullable=False),
    sa.Column('sim_number', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('shop_id', 'sim_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_sim')
    # ### end Alembic commands ###
