"""adding shop sim table

Revision ID: 8d1123649cb5
Revises: 80541889807e
Create Date: 2020-09-24 11:41:26.390528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d1123649cb5'
down_revision = '80541889807e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_sim')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_sim',
    sa.Column('shop_id', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('sim_number', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('shop_id', 'sim_number'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
